---
version: 3

### DEFINE OPTIONS ###
options:
  package_manager_path: /usr/bin/microdnf

### DEFINE IMAGES ###
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

build_arg_defaults:
 ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

dependencies:
  python:
    - pywinrm==0.5.0
