---
- name: Check which host is running the playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print the hostname
      debug:
        msg: "{{ ansible_fqdn }}"

- name: Test connection
  hosts: alex-mac
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Test connection
      ping:

    - name: Ensure /tmp directory exists
      file:
        path: /tmp/test/hello
        state: directory
        mode: '0777'

    - name: Create a file on my VM
      copy:
        content: "Hello, world!"
        dest: /tmp/test/hello/hello.txt
