---
- name: Simple Linux Playbook
  hosts: localhost
  become: true  # This allows Ansible to use sudo
  gather_facts: false
  tasks:

    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'

    - name: Generate SSH key pair
      command: ssh-keygen -t rsa -b 2048 -f /home/{{ ansible_user }}/.ssh/id_rsa -N ''
      args:
        creates: /home/{{ ansible_user }}/.ssh/id_rsa

    - name: Display public key
      shell: cat /home/{{ ansible_user }}/.ssh/id_rsa.pub
      register: public_key_output

    - name: Show public key
      debug:
        msg: "{{ public_key_output.stdout }}"
