---
- name: Check pywinrm
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check pywinrm
      command: pip3 --version
    
    - name: Cat krb5.conf
      command: cat /etc/krb5.conf.d/krb5.conf
    
    - name: pause for 50 seconds
      pause:
        minutes: 5

# - name: Test
#   hosts: rooalien
#   become: false
#   gather_facts: false
#   tasks:
#     - name: Debug
#       win_ping:

#     - name: Get whoami information
#       win_whoami:
    
#     - name: Cat krb5.conf
#       win_command: type C:\etc\krb5.conf
